### ISSUE TITLE
View [Minimal] Not Found

### ISSUE THREAD

**Issue by jonnysaur** [percymamedy/birdboard#1]
Hi, I'm fairly new to laravel and I keep getting this error exception when trying to access the application. any ideas ?

![Screenshot 2020-03-04 at 9 10 52 PM](https://user-images.githubusercontent.com/23029775/75882977-360ccf00-5e5d-11ea-937d-d5bd35b5a857.png)

**Comment by percymamedy** [comment]
Ask on Laracast Forum. This is a Demo Project.
